# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

# Core definitions
.core-defs:
  variables:
    MAKEFILE: Makefile.libretro
    CORENAME: mame

# Core definitions
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-make.yml'
    
  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'
    
  ################################## CONSOLES ################################
  # # Nintendo 3DS
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/ctr-static.yml'
    
  # # Nintendo WiiU
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/wiiu-static.yml'

  # # Nintendo Switch
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/libnx-static.yml'

  # # PlayStation Vita
  # - project: 'libretro-infrastructure/ci-templates'
  #   file: '/vita-static.yml'
  
  # tvOS (AppleTV)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-arm64.yml'
  
  #################################### MISC ##################################

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

# Cache
# Need to set a proper key in each job
cache: &global_cache
  untracked: true
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - build/

##############################################################################
#################################### STAGES ##################################
##############################################################################

################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-amd64-ubuntu:latest
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - sudo apt-get update -qy
    - sudo apt-get install -qy software-properties-common
    - sudo add-apt-repository -y ppa:savoury1/build-tools
    - sudo add-apt-repository -y ppa:savoury1/gcc-defaults-12
    - sudo apt-get update -qy
    - sudo apt-get install -qy gcc-12 g++-12
  # This container's existing installations of gcc and CMake are way too old
  variables:
    OVERRIDE_CC: /usr/bin/gcc-12
    OVERRIDE_CXX: /usr/bin/g++-12
    CXXFLAGS: -Wno-deprecated-declarations # Deprecation warnings aren't helpful on the libretro Gitlab
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-i386-ubuntu:latest
  before_script:
    - export NUMPROC=$(($(nproc)/5))
    - sudo apt-get update -qy
    - sudo apt-get install -qy software-properties-common
    - sudo add-apt-repository -y ppa:savoury1/build-tools
    - sudo add-apt-repository -y ppa:savoury1/gcc-defaults-12
    - sudo apt-get update -qy
    - sudo apt-get install -qy gcc-12 g++-12
  # This container's existing installations of gcc and CMake are way too old
  variables:
    OVERRIDE_CC: /usr/bin/gcc-12
    OVERRIDE_CXX: /usr/bin/g++-12
    CXXFLAGS: -Wno-deprecated-declarations # Deprecation warnings aren't helpful on the libretro Gitlab
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/
    
# MacOS 64-bit
libretro-build-osx-x64:
  tags:
    - macosx-packaging
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.14"
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  tags:
    - macosx-packaging
  extends:
    - .libretro-osx-arm64-make-default
    - .core-defs
  variables:
    MACOSX_DEPLOYMENT_TARGET: "10.14"
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/
    
################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-make-armeabi-v7a
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-make-arm64-v8a
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Android ARMv8a (mess)
android-arm64-v8a-mess:
  extends:
    - .libretro-android-make-arm64-v8a
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: mess
    CORENAME:  mamemess
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-make-x86_64
    - .core-defs
  variables:
    TARGET:    mame
    SUBTARGET: arcade
    CORENAME:  mamearcade
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/
    
# # Android 32-bit x86
# android-x86:
#   extends:
#     - .libretro-android-jni-x86
#     - .core-defs

# iOS
libretro-build-ios-arm64:
  tags:
    - macosx-packaging
  extends:
    - .libretro-ios-arm64-make-default
    - .core-defs
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/

# tvOS
libretro-build-tvos-arm64:
  tags:
    - macosx-packaging
  extends:
    - .libretro-tvos-arm64-make-default
    - .core-defs
  cache:
    <<: *global_cache
  only:
    - master
    - /^libretro/mame.*$/
    
################################### CONSOLES #################################
# # Nintendo 3DS
# libretro-build-ctr:
#   extends:
#     - .libretro-ctr-static-retroarch-master
#     - .core-defs
    
# # Nintendo WiiU
# libretro-build-wiiu:
#   extends:
#     - .libretro-wiiu-static-retroarch-master
#     - .core-defs

# # Nintendo Switch
# libretro-build-libnx-aarch64:
#   extends:
#     - .libretro-libnx-static-retroarch-master
#     - .core-defs

# # PlayStation Vita
# libretro-build-vita:
#   extends:
#     - .libretro-vita-static-retroarch-master
#     - .core-defs
